{{- if .Values.dbInitJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: {{ .Values.namespace.name }}
  labels:
    app: db-init
    app.kubernetes.io/part-of: bankapp
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  backoffLimit: {{ .Values.dbInitJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.dbInitJob.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: {{ .Values.dbInitJob.restartPolicy }}
      volumes:
        - name: init-script
          configMap:
            name: db-init-script
            items:
              - key: init.sql
                path: init.sql
      containers:
        - name: db-init
          image: {{ .Values.dbInitJob.image }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Waiting for DB..."
              until pg_isready -h $DB_HOST -U $DB_USER; do
                sleep 2
              done
              echo "Running init.sql..."
              PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f /scripts/init.sql
              echo "DB init completed"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bankapp-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bankapp-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bankapp-backend-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bankapp-backend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bankapp-backend-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: init-script
              mountPath: /scripts
              readOnly: true
{{- end }}