apiVersion: v1
kind: Secret
metadata:
  name: bankapp-backend-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/part-of: bankapp
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DB_NAME:     {{ .Values.secrets.dbName | b64enc | quote }}
  DB_USER:     {{ .Values.secrets.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  JWT_SECRET:  {{ .Values.secrets.jwtSecret | b64enc | quote }}