  ## change according to your env and create kubernetes/secret.yaml file
apiVersion: v1
kind: Secret
metadata:   
  name: bankapp-backend-secret
  labels:
    app.kubernetes.io/part-of: bankapp
  namespace: bankapp
type: Opaque
data: 
  DB_USER: cG9zdGdyZXMK  ## echo -n 'username' | base64
  DB_PASSWORD: VzZITSZoKTtjbEgpCg== ## echo -n 'secure_password' | base64
  DB_NAME: YmFua2RhdGEK  ## echo -n 'bankdata' | base64
  JWT_SECRET: aUwvM3FOQS80ODVlMzJsMFE3UEtxYW1vR3hkSW93PT0K