  ## change according to your env and create kubernetes/secret.yaml file
apiVersion: v1
data:
  DB_NAME: YmFua2FwcA==           ## echo -n 'bankapp' | base64
  DB_PASSWORD: bSgwSy0jWU1BR3lCPnI/SzU6MDVWTExQJDM8Ng==   ## echo -n 'secure_password' | base64
  DB_USER: ZGJhZG1pbg==          ## echo -n 'username' | base64
  JWT_SECRET: cnF2YlJlaWtBMjFUQkJ2VXhEWjZLODdhWWlxODdXWnVlVW9Iem1Dd2xEQSt5WTEzTHoxa1l2Um1BaUwvM3FOQS80ODVlMzJsMFE3UEtxYW1vR3hkSW93PT0=   ## 
kind: Secret 
metadata:
  labels:
    app.kubernetes.io/part-of: bankapp
  name: bankapp-backend-secret
  namespace: bankapp
type: Opaque
