# ── auth-service/service.yaml ────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: bankapp-auth-service
  namespace: bankapp
  labels:
    app.kubernetes.io/part-of: bankapp
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: auth-service-port
    protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
