apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankapp-frontend-ingress
  namespace: bankapp
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    #alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/ID         ## Change this to your certificate ARN 
    #alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb        
  rules:
  - host: example.com   ## Change this to your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bankapp-frontend-service
            port:
              number: 80
  - host: www.example.com  ## Change this to your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bankapp-frontend-service
            port:
              number: 80
