apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace:  bankapp
  labels:
    app.kubernetes.io/part-of: bankapp
data:
  DB_PORT: "5432"
  DB_HOST: "bankapp-dev-postgres.<CLUSTER_NAME>.ap-south-1.rds.amazonaws.com" ## Change this to your RDS endpoint
  JWT_EXPIRE_HOURS: "24"
