apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: bankapp
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:17

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bankapp-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: bankapp-config
              key: DB_PORT

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bankapp-backend-secret
              key: DB_USER

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: bankapp-backend-secret
              key: DB_NAME

        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: bankapp-backend-secret
              key: DB_PASSWORD

        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Waiting for DB..."

            until pg_isready -h $DB_HOST -U $DB_USER; do
              sleep 2
            done

            echo "Running init.sql..."

            psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f /scripts/init.sql

            echo "DB init completed"

        volumeMounts:
        - name: init-script
          mountPath: /scripts

      restartPolicy: Never

      volumes:
      - name: init-script
        configMap:
          name: db-init-script
